# Generated by Django 5.0.4 on 2024-07-12 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
    ]
