# Generated by Django 5.0.4 on 2024-07-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_follow_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='following',
        ),
    ]
