# Generated by Django 5.0.4 on 2024-07-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_follower_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='follower',
        ),
    ]
